title: DevPet Wiki
author:
  name: kh0mka (khomenokk)
  email: "kirya.khomenok@mail.ru"

description: >
  Вики-страница, созданная с использованием Markdown

remote_theme: jekyll/minima

minima:
  skin: dark

social_links:
  - title: DevPet GitHub Web Repository
    icon: github
    url: "https://github.com/kh0mka/DevPet/tree/web"
  - title: Telegram
    icon: telegram
    url: "https://t.me/"