title: DevPet Wiki
author:
  name: kh0mka (khomenokk)
  email: "kirya.khomenok@mail.ru"

description: >
  Вики-страница, созданная с использованием Markdown

remote_theme: jekyll/minima

minima:
  skin: dark

social_links:
  - title: DevPet Wiki Web Repository GitHub
    icon: fa-github
    url: "https://github.com/kh0mka/DevPet/tree/web"
  - title: Author of Project DevPet
    icon: fa-github
    url: "https://github.com/kh0mka/"
  - title: Telegram of Developer
    icon: fa-telegram
    url: "https://t.me/xkhomenok"